apiVersion: apps/v1
kind: Deployment
metadata:
  name: sisbgws-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sisbgws-pod
  template:
    metadata:
      labels:
        app: sisbgws-pod
        jobid: '{{JOB_ID}}'
    spec:
      imagePullSecrets:
        - name: docker-registry-ssp
      containers:
        - name: sisbgws-container
          envFrom:
            - secretRef:
                name: secret-sisbgws
            - configMapRef:
                name: config-sisbgws
          image: docker.ssp.go.gov.br/ssp/sisbgws:{{COMMIT_ID}}
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthcheck #liberar trafego para o POD somente quando a app subir sem problemas (estiver tudo OK)
              port: http
            initialDelaySeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /healthcheck #reiniciar o POD quando a app se tornar UNRESPONSIVE
              port: http
            initialDelaySeconds: 15
            failureThreshold: 3
            periodSeconds: 3
